# Generated by Django 5.1.7 on 2025-04-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('criteria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('checked_by_head', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('criteria', models.ManyToManyField(to='criteria.criteria')),
            ],
        ),
    ]
