# Generated by Django 5.1.7 on 2025-06-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='about_event',
            field=models.TextField(default='mero'),
        ),
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='report',
            name='members',
            field=models.TextField(default='member'),
        ),
        migrations.AddField(
            model_name='report',
            name='proofs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='result',
            field=models.CharField(choices=[('done', 'выполнено'), ('process', 'в процессе'), ('passed', 'сдано'), ('in_work', 'в работе')], default='process', help_text='Результаты', max_length=20),
        ),
    ]
