# Generated by Django 5.1.7 on 2025-05-22 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='affiliation',
            new_name='pck',
        ),
    ]
